GET http://localhost:5000



### Registration Routes 

###         Register
POST  http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "ashish",
    "email": "ashish16@gmail.com",
    "password": "ashish1234",
    "repeat_password": "ashish1234"
}


###         Login
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "ashish@gmail.com",
    "password": "1234567"
}


###         Who m I
GET http://localhost:5000/api/me
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTA3ZGEzOTNiNzkxZDMxMGNmZDg5NzYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MjgwNTg4MzAsImV4cCI6MTY1OTYxNjQzMH0.6x6XktsRcEvCKMLpkkcel7cOGqu4PVueQ3G2VvRhQhc



###         Logout
POST http://localhost:5000/api/logout
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTg5MDAwMTQsImV4cCI6MTYxODkwMDA0NCwiYXVkIjoiNjA3MTRmYzI3MTM0YTgxNTljN2M0YWM3IiwiaXNzIjoiaXRzYS5jb20ifQ.KbowgUQyA5LJi5i7ACTqpSnNO8O98k4gr7KgzZuMHKo
Content-Type: application/json

{
    "refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
    eyJfaWQiOiI2MGZlOTk1ZDM1OTk1YzIxM2MxZmFjZmMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2Mj
    czOTEwNTgsImV4cCI6MTY1ODk0ODY1OH0.gr1P1UwW5rIJ1PIpZlKbdKQyYeTPKo-YtnR3sVqtCH8"
}


###         Refresh-Token
POST  http://localhost:5000/api/refresh
Content-Type: application/json  

{
    "refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
    eyJfaWQiOiI2MGZlOTk1ZDM1OTk1YzIxM2MxZmFjZmMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2Mjc
    zOTEwMzAsImV4cCI6MTY1ODk0ODYzMH0.Z6IcIwN9QmXM1IIlQ04dzw8hL1qvMmtehQYe6vAm4TY"
}











### Products Routes like create products, update products, delete products etc.

GET http://localhost:5000/api/products



###
GET http://localhost:5000/api/products/jskfjksjf
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTg5MDAwMTQsImV4cCI6MTYxODkwMDA0NCwiYXVkIjoiNjA3MTRmYzI3MTM0YTgxNTljN2M0YWM3IiwiaXNzIjoiaXRzYS5jb20ifQ.KbowgUQyA5LJi5i7ACTqpSnNO8O98k4gr7KgzZuMHKo



###
POST http://localhost:5000/api/products
Content-Type: application/json

{
      "name": "boAt Rockerz 450 Bluetooth Headse",
      "description": "With Mic:Yes\nConnector type: 3.5 mm\nBattery life: 15 hr | Charging time: 3 Hours\n40mm Drivers: HD Sound\nAdjustable Earcups",
      "price": "₹1,099",
      "image": "http://localhost:5000/uploads\\boat-rockerz-450-.jpeg-1627909665378-.jpeg",
}




### 
PUT  http://localhost:5000/api/products/61000602ed02611f1c60ea99
Content-Type: application/json

{
      "name": "boAt Rockerz 450 Bluetooth Headse",
      "description": "With Mic:Yes\nConnector type: 3.5 mm\nBattery life: 15 hr | Charging time: 3 Hours\n40mm Drivers: HD Sound\nAdjustable Earcups",
      "price": "₹1,099",
      "image": "http://localhost:5000/uploads\\boat-rockerz-450-.jpeg-1627909665378-.jpeg",
}



### 
DELETE  http://localhost:5000/api/products/6107edcfad1b993520c3a000
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTg5MDAwMTQsImV4cCI6MTYxODkwMDA0NCwiYXVkIjoiNjA3MTRmYzI3MTM0YTgxNTljN2M0YWM3IiwiaXNzIjoiaXRzYS5jb20ifQ.KbowgUQyA5LJi5i7ACTqpSnNO8O98k4gr7KgzZuMHKo

